Avoid keeping script in memory, by nohup-ing the called app

diff --git a/marathon b/marathon
--- a/marathon
+++ b/marathon
@@ -8,6 +8,7 @@ if ! command -v ps > /dev/null; then echo "Missing ps"; missingDeps=true; fi
 if ! command -v awk > /dev/null; then echo "Missing awk"; missingDeps=true; fi
 if ! command -v wmctrl > /dev/null; then echo "Missing wmctrl"; missingDeps=true; fi
 if ! command -v xdotool > /dev/null; then echo "Missing xdotool"; missingDeps=true; fi
+if ! command -v nohup > /dev/null; then echo "Missing nohup"; missingDeps=true; fi
 if [ $missingDeps = true ]; then exit 1; fi
 
 toggle=0
@@ -75,5 +76,5 @@ if [ "$runningInstancesOfExec" -gt "0" ]; then
   fi
 else
   # shellcheck disable=SC2086
-  exec $cmd;
+  nohup $cmd &
 fi
